apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellowebservice
  labels:
    app: hellowebservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellowebservice
  template:
    metadata:
      labels:
        app: hellowebservice
    spec:      
      containers:
      - name: twitterappistudy
        image: myacr66.azurecr.io/app/hellowebservice
        ports:
        - containerPort: 6060

#Added this to expose the access to external url
---
apiVersion: v1
kind: Service
metadata:
  name: hellowebservicelb
spec:
  type: LoadBalancer
  ports:
  - port: 6060
  selector:
    app: hellowebservice